using UnityEngine;

public class EnemyGenerator : MonoBehaviour
{
    //“G
    [SerializeField] GameObject _enemyPrefab;
    //•æ
    [SerializeField] GameObject _tombPrefab;
    //ŠÔŠÔŠu‚ÌÅ¬’l
    [SerializeField] float _minTime = 2f;
    //ŠÔŠÔŠu‚ÌÅ‘å’l
    [SerializeField] float _maxTime = 5f;
    //¶¬êŠX²
    [SerializeField] float _appearancePositionX = 0f;
    //¶¬êŠY²
    [SerializeField] float _appearancePositionY = 0f;
    //¶¬êŠZ²
    [SerializeField] float _appearancePositionZ = 0f;

    //“G¶¬ŠÔŠÔŠu
    private float _interval;
    //Œo‰ßŠÔ
    private float _time = 0f;

    void Start()
    {
        //ŠÔŠÔŠu‚ğŒˆ’è‚·‚é
        _interval = GetRandomTime();
        //•æ‚ğ¶¬
        GameObject tomb = Instantiate(_tombPrefab);
        //¶¬êŠ
        tomb.transform.position = new Vector3(_appearancePositionX,_appearancePositionY,_appearancePositionZ);
    }

    void Update()
    {
        //ŠÔŒv‘ª
        _time += Time.deltaTime;

        //¶¬ŠÔ‚æ‚è‘å‚«‚­‚È‚Á‚½‚Æ‚«)
        if (_time > _interval)
        {
            //enemy¶¬‚·‚é
            GameObject enemy = Instantiate(_enemyPrefab);
            //¶¬‚µ‚½“G‚ÌÀ•W‚ğŒˆ’è‚·‚é(
            enemy.transform.position = new Vector3(_appearancePositionX, _appearancePositionY, _appearancePositionZ);
            //Œo‰ßŠÔ‚ğ‰Šú‰»
            _time = 0f;
            //Ÿ‚ÌŠÔŠÔŠu‚ğŒˆ’è‚·‚é
            _interval = GetRandomTime();
        }
    }

    //ƒ‰ƒ“ƒ_ƒ€‚ÈŠÔ‚ğ¶¬‚·‚é
    private float GetRandomTime()
    {
        return Random.Range(_minTime, _maxTime);
    }
}
